controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_joint_01
      - arm_joint_02
      - arm_joint_03
      - arm_joint_04
      - cluedo_joint
    constraints:
      goal_time: 0.6
      # vel_tolerance is 0 for due to the movegroup/follow_joint_trajectory/goal tolerance is empty
      stopped_velocity_tolerance: 0
      arm_joint_01: {trajectory: 0.1, goal: 0.1}
      arm_joint_02: {trajectory: 0.1, goal: 0.1}
      arm_joint_03: {trajectory: 0.1, goal: 0.1}
      arm_joint_04: {trajectory: 0.1, goal: 0.1}
      cluedo_joint: {trajectory: 0.1, goal: 0.1}
initial:  # Define initial robot poses per group
  - group: arm
    pose: check