arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm_joint_01
    - arm_joint_02
    - arm_joint_03
    - arm_joint_04
    - arm_base_to_base
    - cluedo_joint
  gains:
    arm_joint_01:
      p: 40
      d: 0
      i: 0
      i_clamp: 0
    arm_joint_02:
      p: 46
      d: 0
      i: 7
      i_clamp: 7
    arm_joint_03:
      p: 50
      d: 0
      i: 7.3
      i_clamp: 7.3
    arm_joint_04:
      p: 43
      d: 0.002
      i: 0.45
      i_clamp: 0.45
    cluedo_joint:
      p: 38
      d: 0.40
      i: 0.13
      i_clamp: 0.13
    arm_base_to_base:
      p: 60
      d: 0.5
      i: 1
      i_clamp: 1