arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - arm_joint_01
    - arm_joint_02
    - arm_joint_03
    - arm_joint_04
    - arm_base_to_base
    - cluedo_joint
  gains:
    arm_joint_01:
      p: 40
      d: 0
      i: 0
      i_clamp: 0
    arm_joint_02:
      p: 50
      d: 0.1
      i: 0.09
      i_clamp: 0.09
    arm_joint_03:
      p: 30
      d: 0
      i: 0.1
      i_clamp: 0.1
    arm_joint_04:
      p: 27
      d: 0.03
      i: 0.2
      i_clamp: 0.2
    cluedo_joint:
      p: 25
      d: 0.03
      i: 0.25
      i_clamp: 0.25
    arm_base_to_base:
      p: 50
      d: 0.5
      i: 0.001
      i_clamp: 0.001